version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: covid-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ventisette
    ports:
      - "5432:5432"

