spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://postgres:5432/covid-db
    username: postgres
    password: ventisette
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
