// Test de création d'un nouveau superadmin (SUPER ADMIN)
POST http://localhost:8080/api/superadmins
Content-Type: application/json

{
    "nom": "John",
    "prenom": "Doe",
    "email": "johndoe@example.com",
    "telephone": "1234567890"
}

###
// Test de lecture d'un superadmin par l'Id (SUPER ADMIN)
GET http://localhost:8080/api/superadmins/2

###
// Lecture de tous les superadmin (SUPER ADMIN)
GET http://localhost:8080/api/superadmins

###
// Modification d'un superadmin (SUPER ADMIN)
PUT http://localhost:8080/api/superadmins/1
Content-Type: application/json

{
    "nom": "Johnnnn",
    "prenom": "Doe",
    "email": "johndoe@example.com",
    "telephone": "1234567890"
}

###
// Test de suppression d'un superadmin par l'Id (SUPER ADMIN)
DELETE http://localhost:8080/api/superadmins/1

###################################################################

###
//Test de recuperation d'un centre par le nom de sa ville (PUBLIC) 
GET http://localhost:8080/api/public/centres?ville=Paris

###
//Test d'inscription à un centre (PUBLIC)
POST http://localhost:8080/api/public/inscriptions
Content-Type: application/json

{
    "nom": "MO",
    "prenom": "Hamza",
    "email": "email@example.com",
    "telephone": "123456789",
    "dateInscription": "2023-09-23",
    "centre": {
        "id": 1
    }
}


################################################################

###
//Test de creation d'un nouvau centre (SUPER ADMIN)
POST http://localhost:8080/api/superadmin/centres
Content-Type: application/json

{
    "nom": "Centre Meneau",
    "adresse": "123 Rue de Test",
    "ville": "Strasbourg"
}

###
//Test de lecture d'un centre par l'Id (SUPER ADMIN)
GET http://localhost:8080/api/superadmin/centres/1

###
//Lecture de tous les centres (SUPER ADMIN)
GET http://localhost:8080/api/superadmin/centres

###
//Modification d'un centre (SUPER ADMIN)
PUT http://localhost:8080/superadmin/centres/2
Content-Type: application/json

{
    "nom": "centre",
    "adresse": "123 Rue de Test",
    "ville": "Biella"
}

###
//Test de suppression d'un centre par l'Id (SUPER ADMIN)
DELETE http://localhost:8080/superadmin/centres/1


################################################################

###
//Test de creation d'un nouvau administrateur (SUPER ADMIN)
POST http://localhost:8080/api/superadmin/administrateurs
Content-Type: application/json

{
    "nom": "Gio",
    "prenom":"Dupont",
    "email": "email@example.com",
    "telephone": "123456789",
    "centre": {
        "id": 1
    }
}

###
//Test de lecture des administrateurs par l'Id du centre (SUPER ADMIN)
GET http://localhost:8080/api/superadmin/administrateurs/centre/1

###
//Lecture de tous les administrateurs (SUPER ADMIN)
GET http://localhost:8080/api/superadmin/administrateurs

###
//Modification d'un administrateur (SUPER ADMIN)
PUT http://localhost:8080/api/superadmin/administrateurs/1
Content-Type: application/json

{
    "nom": "Hamzaaaaaa",
    "prenom":"Dupont",
    "email": "email@example.com",
    "telephone": "123456789",
    "centre": {
        "id": 1
    }
}

###
//Test de suppression d'un administarteur par l'Id
DELETE http://localhost:8080/api/superadmin/administrateurs/2


################################################################

###
//Test de creation d'un nouvau médecin (ADMIN)
POST http://localhost:8080/api/admin/medecins
Content-Type: application/json

{
    "nom": "Rosa",
    "prenom":"Rosa",
    "email": "email@example.com",
    "telephone": "123456789",
    "centre": {
        "id": 1
    }
}

###
//Test de lecture de l'ensemble des médecin par l'Id de leur centre (ADMIN)
GET http://localhost:8080/api/admin/medecins?centreId=1

###
DELETE  http://localhost:8080/api/admin/medecins/1
###
//Modification d'un medecin (ADMIN)
PUT http://localhost:8080/api/admin/medecins/1
Content-Type: application/json

{
    "nom": "Hamza",
    "prenom":"MO",
    "email": "email@example.com",
    "telephone": "123456789",
    "centre": {
        "id": 1
    }
}



################################################################

###
//Test de lecture des inscriptions liées à un centre (ADMIN)
GET http://localhost:8080/admin/inscriptions?centreId=1


###
//Test de l'effacement d'une inscription suivant son Id (ADMIN)
DELETE http://localhost:8080/admin/inscriptions/1



################################################################

###
//Test de recherche d'une personne par son nom dans l'inscription (On retourne l'inscription) (MEDECIN)
GET http://localhost:8080/admin/medecin/rechercherPersonne?nom=MO

###
//Test de validation de la vaccination d'une personne par son Id d'inscription (MEDECIN)
PUT http://localhost:8080/admin/medecin/validerVaccination/1?medecinId=1


